# Refer: https://aka.ms/yaml

jobs:

  - job: win_vs2019
    displayName: Windows - VS 2019
    pool:
      vmImage: windows-2019
    steps:
      - script: |
          echo Loading VS environment
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\vsdevcmd" -arch=x64 || exit 1
          echo Downloading DDS executable
          pwsh -noni -c iwr https://github.com/vector-of-bool/dds/releases/download/0.1.0-alpha.4/dds-win-x64.exe -OutFile dds.exe || exit 1
          echo Build
          .\dds.exe build -t tools/msvc.jsonc
        displayName: Build and Run Unit Tests

  - job: linux_gcc9
    displayName: Linux - GCC 9
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: |
          set -eu
          sudo apt update -y
          sudo apt install -y g++-9
          echo Downloading DDS executable
          curl -L https://github.com/vector-of-bool/dds/releases/download/0.1.0-alpha.4/dds-linux-x64 -o dds
          chmod +x dds
        displayName: Prepare System
      - script: ./dds build -t tools/gcc-9.jsonc
        displayName: Build and Run Unit Tests

  - job: linux_gcc10
    displayName: Linux - GCC 10
    pool:
      vmImage: ubuntu-20.04
    steps:
      - script: |
          set -eu
          sudo apt update -y
          sudo apt install -y g++-10
          echo Downloading DDS executable
          curl -L https://github.com/vector-of-bool/dds/releases/download/0.1.0-alpha.4/dds-linux-x64 -o dds
          chmod +x dds
        displayName: Prepare System
      - script: ./dds build -t tools/gcc-10.jsonc
        displayName: Build and Run Unit Tests

  - job: macos_gcc9
    displayName: macOS - GCC 9
    pool:
      vmImage: macOS-10.15
    steps:
      - script: |
          set -eu
          brew install gcc@9
          echo Downloading DDS executable
          curl -L https://github.com/vector-of-bool/dds/releases/download/0.1.0-alpha.4/dds-macos-x64 -o dds
          chmod +x dds
        displayName: Prepare System
      - script: ./dds build -t tools/gcc-9.jsonc
        displayName: Build and Run Unit Tests

  - job: macos_gcc10
    displayName: macOS - GCC 10
    pool:
      vmImage: macOS-10.15
    steps:
      - script: |
          set -eu
          brew install gcc@10
          echo Downloading DDS executable
          curl -L https://github.com/vector-of-bool/dds/releases/download/0.1.0-alpha.4/dds-macos-x64 -o dds
          chmod +x dds
        displayName: Prepare System
      - script: ./dds build -t tools/gcc-10.jsonc
        displayName: Build and Run Unit Tests
